xcache: #【1】 xcache 配置根节点
  group: shop #【2】分组名称（必填），主要用于区分不同的应用
  template: #【3】公共模板配置（必填），列表类型，可配置一至多个
    - id: t0 #【4】模板ID（必填）
      first: #【5】一级缓存配置
        provider: caffeine #【6】使用 id 为 caffeine 的 StoreProvider 创建一级缓存实例
      second: #【7】二级缓存配置
        provider: lettuce #【8】使用 id 为 lettuce 的 StoreProvider 创建二级缓存实例（即【11】中设定的 id）
  redis: #【9】Redis 配置
    lettuce: #【10】Lettuce 配置
      - id: lettuce #【11】RedisOperatorFactory, RedisStoreProvider …… 唯一标识（默认值：lettuce）
        compatible: true #【12】 兼容模式配置，如使用 Redis-Compatible DB，如 Pika，请设为 true（默认值：false）
        standalone: #【13】单机模式（或副本集模式）配置
          node: 192.168.50.157:9221 #【14】节点地址