xcache: #【1】 xcache 配置根节点
  group: shop #【2】分组名称（必填），主要用于区分不同的应用
  template: #【3】缓存公共配置模板（必填），列表类型，可配置一至多个
    - id: t0 #【4】 模板ID（必填）
      first: #【5】 一级缓存配置
        provider: caffeine #【6】使用 id 为 caffeine 的 StoreProvider 创建一级缓存实例（默认值：caffeine）